version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: book-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=book_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book-network

  redis:
    image: redis:7-alpine
    container_name: book-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - book-network

volumes:
  postgres_data:
  redis_data:

networks:
  book-network:
    driver: bridge