app:
  redis:
    enable: true
  cache:
    cacheType: redis
    cacheNames:
      - bookByTitleAndAuthor
      - booksByCategory
    caches:
      bookByTitleAndAuthor:
        expiry: 10m
      booksByCategory:
        expiry: 15m

spring:
  application:
    name: skillbox-integration-demo
  datasource:
    url: jdbc:postgresql://localhost:5433/book_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    com.example.skillboxintegrationdemo: DEBUG
    org.hibernate.SQL: DEBUG
